spring:
  application:
    name: spring-cloud-eureka-feign-client
  jmx:
    enabled: false
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}